invoice_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('login.urls')),
    path('invoices/', include('invoice.urls')),
    path('customers/', include('customer.urls')),
    path('checkout/', include('checkout.urls')),
    path('sage/', include('sage.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sage_auth', views.sage_auth, name='sage_auth'),
    path('test', views.test, name='test'),
    path('sage_callback', views.sage_callback, name='sage_callback'),
    path('make_api_request', views.make_api_request, name='make_api_request'),
]

customer/models.py
from django.db import models
from django.utils.text import slugify 


class Customer(models.Model):
    

    class CustomerType(models.IntegerChoices):
        TRADE = 1, 'Trade'
        PRIVATE = 2, 'Private'


    class PaymentTerms(models.IntegerChoices):
        PIA = 1, 'Payment in advance'
        NET_7 = 2, '7 days'
        NET_14 = 3, '14 days'
        NET_30 = 4, '30 days'
        NET_60 = 5, '60 days'


    name = models.CharField(max_length=20, blank=False, null=False)
    friendly_name = models.CharField(max_length=10, blank=True, null=True)
    type = models.PositiveSmallIntegerField(
        choices=CustomerType.choices, blank=True, null=True)
    address_line_1 = models.CharField(max_length=27, blank=True, null=True)
    address_line_2 = models.CharField(max_length=27, blank=True, null=True)
    city_region = models.CharField(max_length=27, blank=True, null=True)
    postcode = models.CharField(max_length=10, blank=True, null=True)
    contact_number_primary = models.CharField(max_length=20, blank=True, null=True)
    email = models.CharField(max_length=20, blank=True, null=True)
    payment_terms = models.PositiveSmallIntegerField(
        choices=PaymentTerms.choices, blank=True, null=True)
    active = models.BooleanField(default=True, blank=True, null=True)

    # utilities
    slug = models.SlugField(max_length=100, unique=True, blank=False, null=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.name}')
        super(Customer, self).save(*args, **kwargs)


class Vehicle(models.Model):

    customer = models.ForeignKey(
        Customer, blank=False, null=False, on_delete=models.CASCADE)
    registration = models.CharField(max_length=10, null=False, blank=False)
    make = models.CharField(max_length=27, blank=True, null=True)
    model = models.CharField(max_length=27, blank=True, null=True)
    active = models.BooleanField(default=True, blank=True, null=True)

    # utilities
    slug = models.SlugField(max_length=100, unique=True, blank=False, null=False)

    def __str__(self):
        return self.registration

    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.registration}')
        super().save(*args, **kwargs)

    
    


    
    

templates/includes/invoice_complete.html
{% load custom_tags %}
{% load static %}
<div class="text-center mb-3">
    <h1>Your invoice {{item.invoice_number}}</h1>
</div>

<div class="container">
    <div class="complete-invoice-container px-md-5">
        <!-- INVOICE DETAILS  -->
        <div class="row">
            <h4>Invoice details</h4>
            <div class="col-12 col-md-6 mb-3">
                <p>{{item.customer}}</p>
                <p>{{item.customer.address_line_1}}</p>
                <p>{{item.customer.address_line_2}}</p>
                <p>{{item.customer.city_region}}</p>
                <p>{{item.customer.postcode}}</p>
            </div>
            <div class="col-12 col-md-6 mb-3 text-end">
                <p>Invoice number: {{item.inv_number}}</p>
                <p>Vehicle: {{item.vehicle.registration}}</p>
                <p>Mileage: {{item.mileage}}</p>
                <p>Date in: {{item.date_in|date_uk}}</p>
                <p>Invoice terms: {{item.customer.get_payment_terms_display}}</p>
            </div>
        </div>
        <!-- PARTS  -->
        <div class="row">
            <h4>Parts details</h4>
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table minimal-table">
                        <tbody>
                            {% for part in parts_list %}
                            <tr>
                                <td class="col-6 content-to-copy">{{part.title}}</td>
                                <td class="col-3 text-end">QTY: {{part.quantity}}</td>
                                <td class="col-3 text-end">{{part.total|format_currency}}</td>
                            </tr>
                            {% endfor %}                    
                            <tr class="bottom-row">
                                <td class="col-6"></td>
                                <td class="col-3 text-end"></td>
                                <td class="col-3 text-end">Subtotal: {{item.parts_total|format_currency}}</td>
                            </tr>
                        </tbody>
                    </table>                
                </div>

            </div>
        </div>

        <!-- LABOUR  -->
        <div class="row">
            <h4>Labour details</h4>
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table minimal-table">
                        <tbody>
                            {% for labour in labour_list %}
                            <tr>
                                <td class="col-6 content-to-copy">{{labour.description}}</td>
                                <td class="col-3 text-end">HRS: {{labour.hours}}</td>
                                <td class="col-3 text-end">{{labour.total|format_currency}}</td>
                            </tr>
                            {% endfor %}
                            <tr class="bottom-row">
                                <td class="col-6"></td>
                                <td class="col-3 text-end"></td>
                                <td class="col-3 text-end">Subtotal: {{item.labour_total|format_currency}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <!-- TOTALS  -->
        <div class="row mb-5">
            <div class="col-12">
                <h4 class="">Totals</h4>
                <div class="">
                    <p>Parts: {{item.parts_total|format_currency}}</p>
                    <p>Labour: {{item.labour_total|format_currency}}</p>
                    <p>Subtotal: {{item.subtotal|format_currency}}</p>
                    <p>VAT: {{item.vat_total|format_currency}}</p>
                    <p>Grand Total: {{item.grand_total|format_currency}}</p>
                </div>
            </div>
        </div>
    </div>
</div>

templates/includes/invoice_totals.html
{% load custom_tags %}
Parts: {{item.parts_total|format_currency}}<br>
Labour: {{item.labour_total|format_currency}}<br>
Subtotal: {{item.subtotal|format_currency}}<br>
<hr class="m-1">
VAT: {{item.vat_total|format_currency}}<br>
Total: {{item.grand_total|format_currency}}

templates/includes/searchbar.html
<div class="input-group mb-3">
    <input id="search-bar" type="text" class="form-control" placeholder="Search" aria-label="Search"
        aria-describedby="search-confirm" name="q">
    <input type="hidden" name="filter" value="{{ filter_status }}">
    <button class="btn btn-outline-secondary" type="submit" id="search-confirm"><i class="bi bi-search"></i></button>
</div>